# Generated by Django 4.2.4 on 2023-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_userapp', '0002_rename_address_customuser_phone_unmber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_unmber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', '기타(Other)'), ('W', '여성(Woman)'), ('M', '남성(Man)')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
