# Generated by Django 4.2.4 on 2023-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_userapp', '0003_rename_phone_unmber_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', '기타(Other)'), ('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
