# Generated by Django 4.2.1 on 2023-08-12 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('with_medicine_review', '0002_review_board_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='review_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
