# Generated by Django 4.2.1 on 2023-08-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_review', '0003_review_board_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_board',
            old_name='like_users',
            new_name='review_users',
        ),
    ]
