# Generated by Django 4.2.1 on 2023-08-12 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('with_medicine_review', '0004_rename_like_users_review_board_review_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_board',
            old_name='review_users',
            new_name='like_users',
        ),
        migrations.AlterField(
            model_name='review_board',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
