# Generated by Django 4.2.1 on 2023-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_review', '0005_rename_review_users_review_board_like_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
