# Generated by Django 4.2.1 on 2023-08-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_free', '0004_free_board_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_board',
            name='hits',
        ),
    ]
