# Generated by Django 4.2.4 on 2023-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_free', '0005_remove_free_board_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_board',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
