# Generated by Django 4.2.1 on 2023-08-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_free', '0006_free_board_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_board',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
