# Generated by Django 4.2.1 on 2023-08-13 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_free', '0007_alter_free_board_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_board',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data published'),
        ),
    ]
