# Generated by Django 4.2.1 on 2023-08-15 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('with_medicine_free', '0007_free_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_comment',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_posts_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
